### ISSUE TITLE
Implement IProgress<int> and IProgress<string> in ProgressDialog

### ISSUE THREAD

**Issue by vpenades** [ookii-dialogs/ookii-dialogs-wpf#12]
it could be very useful if ProgressDialog would implement these interfaces:

`System.IProgress<int>`   to report progress percentage
`System.IProgress<Text>` to report textual progress

So the ProgressDialog object could be passed as a plain object to the running jobs, and casted to `IProgress<int>` and `IProgress<Text>` for progress reporting

**Comment by caioproiete** [comment]
Thanks @vpenades, that sounds like a great idea.

Let me know if you'd like to take a stab at it and send a PR, otherwise I'll get to it soon for the next release.

**Comment by vpenades** [comment]
PR ready...

**Comment by augustoproiete** [comment]
@vpenades Ookii.Dialogs.Wpf now supports .NET 5 as well as .NET Core 3.1, so I thought I'd ping you in case you ever want to start discussing possible improvements to the `IProgress<T>` implementation

ps: Don't feel obligated to reply. This is just a friendly ping given your prior interest in this.

**Comment by vpenades** [comment]
Well, it's just about improving the funcionality, and having a rich progress reporting, while keeping the abstraction.

It is very tempting to have a structure that keeps all the information required by the progress dialog (percent, text, description), but this _must be avoided_  because that would mean the caller needs to fill that structure, which would force it to have a dependency on the ookii library, this is probably not desirable for background tasks, or pure code libraries that don't want to depend on an UI library.

So, in order to pass rich progress information, we need to use only BCL types and collections. Unfortunately, IProgress<T> does not define a standard....   but in general I guess everybody will expect (int Percent, string Text, string Description)

So, I would propose adding these interface:

```c#
IProgress< KeyValuePair<string,object> > // where key is the name of the property to set (percent, text, desc)
```

Additionally, the current IProgress<int> and IProgress<string> could cache the content so they're not mutually exclusive; the current code already caches the progress, but it should do the same with the text. So a background task could call these interfaces consecutively without loosing the value set by the previous call on the other property.

**Comment by augustoproiete** [comment]
Tracking the implementation of `IProgress<T>` on https://github.com/ookii-dialogs/ookii-dialogs-wpf/issues/58 and closing this one as completed in Ookii Dialogs v1.2.0
