### ISSUE TITLE
Add support for selecting multiple folders in VistaFolderBrowserDialog

### ISSUE THREAD

**Issue by augustoproiete** [ookii-dialogs/ookii-dialogs-wpf#29]
The API supports `FOS_ALLOWMULTISELECT` but an option to set it is not exposed in the `VistaFolderBrowserDialog`

**Comment by lozo2010** [comment]
Good job! I will try to help

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Ookii.Dialogs.Wpf v5.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/ookii-dialogs/ookii-dialogs-wpf/releases/tag/v5.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/5.0.0)
