### ISSUE TITLE
Add Preview for some file extension in openFileDialog Preview Pane

### ISSUE THREAD

**Issue by MuhammadSulaiman001** [ookii-dialogs/ookii-dialogs-wpf#38]
Help wanted

**Comment by augustoproiete** [comment]
Hi @MuhammadSulaiman001 would you be able to provide more details about how do you see that working? Which extensions, how the preview would look like for each kind of extension, etc.?

ps: I'm moving this to the discussions area, until we have enough scope for an issue that can be worked on.
