### ISSUE TITLE
Allow additional entropy for password encryption

### ISSUE THREAD

**Issue by Koekiewollie** [ookii-dialogs/ookii-dialogs-wpf#40]
The credentials dialog allows users to save their password. This password is then encrypted and saved.
The encryption of the password allows for an additional entropy to increase the complexity.
This will make it harder for malicious software to retrieve the password in a situation when it manages to run at current user level.

The proposal is to be able to set the entropy on the credential dialog, so it can be used for the password encryption/decryption.

For more information, see:
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata.protect?view=net-5.0

**Comment by augustoproiete** [comment]
Closed by #41
