### ISSUE TITLE
Progress bar is empty

### ISSUE THREAD

**Issue by virzak** [ookii-dialogs/ookii-dialogs-wpf#86]
Not sure if this is the underlying control issue or not, but the progress bar isn't updating.

![image](https://user-images.githubusercontent.com/6209775/146412356-f54cdb57-4787-40a1-ba32-240ec46cc206.png)

Marquee mode works fine though.

**Comment by augustoproiete** [comment]
Thanks for reporting @virzak this will be fixed shortly in v5.0.1

**Comment by augustoproiete** [comment]
:tada: This issue has been resolved in **Ookii.Dialogs.Wpf v5.0.1**

The release is available on:

- :rocket: [GitHub Release](https://github.com/ookii-dialogs/ookii-dialogs-wpf/releases/tag/v5.0.1)
- :package: [NuGet Package](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/5.0.1)
